<?php
$helper = $this->helper("Msp\CustomerPic\Helper\Data");
$isEnable = $helper->isEnable();
?>
<?php if( $isEnable ): ?>
<div class="block block-dashboard-info">
	<div class="block-title"><strong><?php echo __('Profile Picture'); ?></strong></div>
	<div class="block-content">
		<div class="box box-information">
			<strong class="box-title">
				<span><?php echo __('Profile Picture'); ?></span>
			</strong>
			<div class="box-content">
				<?php if( $this->getProfilePic() ): ?>
					<img src="<?php echo $this->getProfilePic(); ?>" width="150">
				<?php else: ?>
					<img src="<?php echo $this->getViewFileUrl('Msp_CustomerPic::images/default.jpg'); ?>" width="150"/>
				<?php endif; ?>
			</div>
		</div>
		<div class="box box-newsletter">
			<strong class="box-title">
				<span><?php echo __('Upload New Profile Picture'); ?></span>
			</strong>
			<div class="box-content">
				<form action="<?php echo $this->getUrl('profile_pic/upload/save'); ?>" enctype="multipart/form-data" method="POST">
					<input type="file" name="profile_pic" accept="image/*">
					<button type="submit"><span><?php echo __('Upload'); ?></span></button>
				</form>
			</div>
		</div>
	</div>
</div>
<?php endif; ?>