<?php
$productData = $block->getData();
// $productId = $productData['data']['currentproductid'];
$registerData = $block->getAllRegisterData();
// foreach ($registerData as $key => $value) {
// 	echo "<pre>";print_r($value->getData());
// }exit();
?>
<div>
  <table>
  <tbody><tr>
    <th style="width:15%">Name</th>
    <th style="width:65%">Birthdate</th>
    <th style="width:15%">Age</th>
    <th style="width:15%">Mobile</th>
  </tr>
  <?php foreach ($registerData as $item): ?>
  <tr>
    <td><?php echo $item->getName(); ?></td>
    <td><?php echo $item->getBirthdate(); ?></td>
    <td><?php echo $item->getAge(); ?></td>
    <td><?php echo $item->getMobile(); ?></td>
  </tr>
<?php endforeach ?>
</tbody>
</table>
</div>
