<div class="field skype required">
    <label class="label" for="skype">
      <span><?= $block->escapeHtml(__('Skype Account')) ?></span>
    </label>
    <div class="control">
       <input type="text" name="skype" id="skype" value="" title="<?= $block->escapeHtmlAttr(__('Skype Account')) ?>" class="input-text" data-validate="{required:true}">
    </div>
</div>
<div class="field phone_number required">
    <label class="label" for="phone_number">
      <span><?= $block->escapeHtml(__('Mobile Number')) ?></span>
    </label>
    <div class="control">
       <input type="text" name="phone_number" id="phone_number" value="" title="<?= $block->escapeHtmlAttr(__('Mobile Number')) ?>" class="input-text" data-validate="{required:true}">
    </div>
</div>
